baseurl = "/"
DefaultContentLanguage = "en"
title = "gywn's tech"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
enableGitInfo = true

[Services]
#   [Services.Disqus]
#     # Shortname = "XXX"
  [Services.googleAnalytics]
    id = "G-N3PQP14SFN"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Innovating, Analyzing, Sharing"
  mainSections = ["post","posts"]
  logo = "img/avatar-sdc-angry.png"
  favicon = "img/favicon-sdc.ico"
# dateFormat = "January 2, 2006"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  since = "2011"
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."
  customCSS = ["css/custom.css"]

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  name = "gywndi"
  website = "https://gywn.net"
  email = "gywndi@gmail.com"
  facebook = "dongchan.sung"
  github = "gywndi"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
